// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://datnpcnmseynlgcvkwwi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhdG5wY25tc2V5bmxnY3Zrd3dpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcyNTg2MTEsImV4cCI6MjA1MjgzNDYxMX0.8_CwjdZdc8D6OuixeXajJ6KaC5dVUvXWm_rOIPyYGDc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);